<?php
namespace App\Http\Livewire\Frontend;

// phpcs:ignoreFile -- this fail is generated by Laravel
/**
 * SenaraiIklanBukaTable File.
 *
 * PHP Version 8.0
 *
 * @category SenaraiIklanBukaTable
 * @package  SenaraiIklanBukaTable
 * @author   Aina <aina@plisca.com.my>
 * @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
 * @link     https://www.plisca.com.my/
 */
use App\Domains\Auth\Models\User;
use Modules\Sisdant\Models\PermohonanNomborPerolehan;
use Modules\Sisdant\Models\IklanPerolehan;
use Modules\Sisdant\Models\MatrikIklan;
use App\Models\Pejabat;
use App\Models\Negeri;
use Modules\Sisdant\Models\JenisIklan;
use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\Views\Filter;
use Carbon\Carbon;

// use Livewire\Component;
/**
 * Class SenaraiIklanBukaTable.
 *
 * @category SenaraiIklanBukaTable
 * @package  SenaraiIklanBukaTable
 * @author   Aina <aina@plisca.com.my>
 * @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
 * @link     https://www.plisca.com.my/
 */
class SenaraiIklanBukaTable extends DataTableComponent
{
    public string $defaultSortColumn = 'created_at';
    public string $defaultSortDirection = 'asc';
    public string $emptyMessage = 'Tiada Data';

    public function columns(): array
    {
        return [
            Column::make(__('Bil')),
            Column::make(__('Negeri'))
            ->sortable(function(Builder $query, $direction) {
                return $query->join('mohon_no_perolehan', 'mohon_no_perolehan.id_perolehan', '=', 'iklan_perolehan.mohon_no_perolehan_id')
                ->orderBy(Negeri::select('negeri')->whereColumn('negeri.id', 'mohon_no_perolehan.negeri_id'), $direction);
            }),
            Column::make(__('No Tender/Projek'))
            ->searchable(function (Builder $query, $term) {
                return $query->where(
                    fn ($query) => $query->whereHas('mohonNoPerolehan', fn($query) => $query
                            ->where('no_perolehan', 'ilike', '%'.$term.'%')
                            ->orWhere('tajuk_perolehan', 'ilike', '%'.$term.'%')
                        )
                    );
                }),
            Column::make(__('Tarikh Iklan'), 'tarikh_keluar_iklan')
            ->sortable(),
            Column::make(__('Tarikh Tutup'), 'tarikh_waktu_tutup')
            ->sortable(),
            Column::make(__('Tempoh Berbaki')),
            Column::make(__('Jenis Iklan')),
            // Column::make(__('Kategori Perolehan')),
            Column::make(__('Tarikh Kemaskini')),
        ];
    }
    /**
     * Builder
     *
     * @return Builder
     */
    public function query(): Builder
    {
        $query = IklanPerolehan::with('user', 'mohonNoPerolehan.matrikIklan.jenisIklan', 'mohonNoPerolehan.matrikIklan.kategoriPerolehan','mohonNoPerolehan.section', 'mohonNoPerolehan.negeri')
        ->join('users', 'mohon_no_perolehan.user_id', '=', 'users.id')->where('users.deleted_at', null)
        ->where('status_iklan_id', 4)
        ->where(function($q) {
            $q->where('tarikh_keluar_iklan', '<=', Carbon::now()->format('Y-m-d'))
              ->where('tarikh_waktu_tutup', '>=', Carbon::now()->format('Y-m-d H:i'));
        });
        // ->get();
        return $query
            ->when($this->getFilter('jenis_iklan'), fn($query, $tags) => $query ->whereHas('mohonNoPerolehan.matrikIklan', fn($query) => $query->whereIn('matrik_iklan.jenis_iklan_id', $tags)));
    }

    /**
     * Filter jenis iklan
     *
     * @return array
     */
    public function filters(): array
    {
        return [
            'jenis_iklan' => Filter::make('JENIS PEROLEHAN')
                ->multiSelect(
                    JenisIklan::query()
                    ->orderBy('nama')
                    ->get()
                    ->keyBy('id')
                    ->map(fn($tag) => $tag->nama)
                    ->toArray()
                ),
        ];
    }

    public function rowView(): string
    {
        return 'livewire.frontend.senarai_iklan_buka';
    }
}
