<?php
namespace App\Http\Livewire\Frontend;

// phpcs:ignoreFile -- this fail is generated by Laravel
/**
 * SenaraiTenderKasaTable File.
 *
 * PHP Version 8.0
 *
 * @category SenaraiTenderKasaTable
 * @package  SenaraiTenderKasaTable
 * @author   Hazwan Fuad <hazwan@plisca.com.my>
 * @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
 * @link     https://www.plisca.com.my/
 */
use App\Domains\Auth\Models\User;
use Modules\Sisdant\Models\PermohonanNomborPerolehan;
use Modules\Sisdant\Models\IklanPerolehan;
use Modules\Sisdant\Models\MatrikIklan;
use App\Models\Pejabat;
use App\Models\Negeri;
use Modules\Sisdant\Models\JenisIklan;
use Modules\Awas\Models\PenilaianPerolehan;
use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;
use Rappasoft\LaravelLivewireTables\Views\Filter;

class SenaraiTenderKasaTable extends DataTableComponent
{
    public string $emptyMessage = 'Tiada Data';

    public function query(): Builder
    {
        $query = IklanPerolehan::join('mohon_no_perolehan', 'mohon_no_perolehan.id_perolehan', '=', 'iklan_perolehan.mohon_no_perolehan_id')
                ->join('matrik_iklan', 'mohon_no_perolehan.matrik_iklan_id', '=', 'matrik_iklan.id')
                ->join('users', 'mohon_no_perolehan.user_id', '=', 'users.id')->where('users.deleted_at', null)
                ->leftJoin('penilaian_perolehan', 'iklan_perolehan.id', '=', 'penilaian_perolehan.iklan_perolehan_id')
                ->where(function($query) {
                    $query->where('status_iklan_id', 5)->where('matrik_iklan.jenis_iklan_id', '2')->where('penilaian_perolehan.status_penilaian', 0);
                })->orderBy('tarikh_waktu_tutup', 'desc');
        return $query;
    }

    public function columns(): array
    {
        return [
            Column::make('Bil', 'id')
                ->sortable(),
            Column::make('Negeri')
                ->sortable(function(Builder $query, $direction) {
                    return $query->join('mohon_no_perolehan', 'mohon_no_perolehan.id_perolehan', '=', 'iklan_perolehan.mohon_no_perolehan_id')
                        ->orderBy(Negeri::select('negeri')->whereColumn('negeri.id', 'mohon_no_perolehan.negeri_id'), $direction);
                }),
            Column::make(__('No Tender/Projek'))
                ->sortable(function(Builder $query, $direction) {
                    return $query->orderBy(PermohonanNomborPerolehan::select('no_perolehan')->whereColumn('mohon_no_perolehan.id_perolehan', 'iklan_perolehan.mohon_no_perolehan_id'), $direction);
                })
                ->searchable(function (Builder $query, $term) {
                    return $query->where(
                        fn ($query) => $query->whereHas(
                            'mohonNoPerolehan',
                            function (
                                $query
                            ) use ($term) {
                                $query->where('no_perolehan', 'like', '%'.$term.'%')
                                    ->orWhere('tajuk_perolehan', 'like', '%'.$term.'%');
                            }
                        )
                    );
                }),
                Column::make('Tarikh Tutup', 'tarikh_waktu_tutup')
                ->sortable(),
                Column::make('Tarikh Kemaskini Penilaian')
                    ->sortable(function(Builder $query, $direction) {
                        return $query->orderBy(PenilaianPerolehan::select('tarikh_kemaskini_penilaian')->whereColumn('penilaian.mohon_no_perolehan_id', 'mohon_no_perolehan.id_perolehan'), $direction);
                    }),
                Column::make('Hantar Ke KASA')

        ];
    }

    public function rowView(): string
    {
        return 'livewire.frontend.senarai_tender_ke_kasa';
    }
}
