version: "3.7"
services:
    app:
        # image: kooldev/php:8.0-nginx
        image: kooldev/php:8.1-nginx
        ports:
            - ${KOOL_APP_PORT:-80}:80
        environment:
            ASUSER: ${KOOL_ASUSER:-0}
            UID: ${UID:-0}
        volumes:
            - .:/app:delegated
        networks:
            - kool_local
            - kool_global
    database:
        image: postgres:13-alpine
        ports:
            - 5432:5432
        environment:
            POSTGRES_DB: spaqs
            POSTGRES_USER: spaqs-user
            POSTGRES_PASSWORD: spaqs-password
            # POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            - database:/var/lib/postgresql/data:delegated
        networks:
            - kool_local
        healthcheck:
            test:
                - CMD
                - pg_isready
                - -q
                - -d
                - $DB_DATABASE
                - -U
                - $DB_USERNAME
    cache:
        image: memcached:1.6-alpine
        volumes:
            - cache:/data:delegated
        networks:
            - kool_local

    redis:
        container_name: laravel-redis
        image: redis:4-alpine
        ports:
            - 6379:6379
        volumes:
            - redis:/data

volumes:
    redis:
        driver: "local"
    database: null
    cache: null
networks:
    kool_local:
        driver: bridge
    kool_global:
        external: true
        name: ${KOOL_GLOBAL_NETWORK:-kool_global}
