<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Events\Negeri;

use App\Models\Negeri;
use Illuminate\Queue\SerializesModels;

/**
 * Class NegeriDeleted.
 */
class NegeriDeleted
{
    use SerializesModels;

    /**
     * @var
     */
    public $negeri;

    /**
     * @param $negeri
     */
    public function __construct(Negeri $negeri)
    {
        $this->negeri = $negeri;
    }
}
