<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Http\Requests\Frontend\User;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Class UpdateProfileRequest.
 */
class UpdateProfileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'nama' => ['required', 'string', 'max:100'],
            'action' => ['string', 'max:100'],
            'no_kad_pengenalan' => ['required', 'numeric', 'digits:12'],
            'negeri' => ['required', 'not_in:none'],
            'bahagian' => ['required_if:negeri,==,16', 'not_in:none'],
        ];
    }
}
