<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
/**
 * IklanTable File.
 *
 * PHP Version 8.0
 *
 * @category IklanTable
 * @package  IklanTable
 * @author   Mimi Khalid <mimi@plisca.com.my>
 * @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
 * @link     https://www.plisca.com.my/
 */
namespace App\Http\Livewire\Backend;
use App\Domains\Auth\Models\User;
use Modules\Sisdant\Models\MatrikIklan;
use Illuminate\Database\Eloquent\Builder;
use Rappasoft\LaravelLivewireTables\DataTableComponent;
use Rappasoft\LaravelLivewireTables\Views\Column;

/**
 * Class IklanTable.
 *
 * @category IklanTable
 * @package  IklanTable
 * @author   Mimi Khalid <mimi@plisca.com.my>
 * @license  http://www.gnu.org/copyleft/gpl.html GNU General Public License
 * @link     https://www.plisca.com.my/
 */
class IklanTable extends DataTableComponent
{
    public string $emptyMessage = 'Tiada Data';

    public function columns(): array
    {
        return [
            Column::make(__('Jenis Iklan'), 'jenis_iklan_id')
                ->sortable()
                ->searchable(),
            Column::make(__('Kategori Perolehan'), 'kategori_perolehan_id')
                ->sortable()
                ->searchable(),
            Column::make(__('Jenis Tender'), 'jenis_tender_id')
                ->sortable()
                ->searchable(),
            Column::make(__('Muatnaik Dokumen'), 'upload_iklan'),
            Column::make(__('Tindakan')),
        ];
    }

    public function query(): Builder
    {
        $query = MatrikIklan::query();
        return $query;

    }

    public function rowView(): string
    {
        return 'backend.auth.iklan.includes.row_matrik_iklan';
    }

}
