<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Events\Iklan;

use Modules\Sisdant\Models\JenisIklan;
use Illuminate\Queue\SerializesModels;

/**
 * Class JenisIklanUpdated.
 */
class JenisIklanUpdated
{
    use SerializesModels;

    /**
     * @var
     */
    public $jenisIklan;

    /**
     * @param $jenisIklan
     */
    public function __construct(JenisIklan $jenisIklan)
    {
        $this->jenisIklan = $jenisIklan;
    }
}
