<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Events\Iklan;

use Modules\Sisdant\Models\KategoriPerolehan;
use Illuminate\Queue\SerializesModels;

/**
 * Class KategoriPerolehanCreated.
 */
class KategoriPerolehanCreated
{
    use SerializesModels;

    /**
     * @var
     */
    public $kategoriPerolehan;

    /**
     * @param $kategoriPerolehan
     */
    public function __construct(KategoriPerolehan $kategoriPerolehan)
    {
        $this->kategoriPerolehan = $kategoriPerolehan;
    }
}
