<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Events\Iklan;

use Modules\Sisdant\Models\MatrikIklan;
use Illuminate\Queue\SerializesModels;

/**
 * Class MatrikIklanCreated.
 */
class MatrikIklanCreated
{
    use SerializesModels;

    /**
     * @var
     */
    public $matrikIklan;

    /**
     * @param $matrikIklan
     */
    public function __construct(MatrikIklan $matrikIklan)
    {
        $this->matrikIklan = $matrikIklan;
    }
}
