<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace Modules\Sisdant\Models;

use Modules\Sisdant\Models\KategoriPerolehan;
use Modules\Sisdant\Models\JenisTender;
use Modules\Sisdant\Models\MatrikIklan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class JenisIklan.
 */
class JenisIklan extends Model
{
    use HasFactory;
    protected $table = 'jenis_iklan';
    protected $fillable = ['id', 'nama', 'updated_at', 'created_at'];

    /**
     * Function for relationship one to many
     */
    public function matrikIklan()
    {
        return $this->hasMany(MatrikIklan::class, 'id');
    }
}
