<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace Modules\Sisdant\Models;

use Modules\Sisdant\Models\JenisIklan;
use Modules\Sisdant\Models\KategoriPerolehan;
use Modules\Sisdant\Models\MatrikIklan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class JenisTender.
 */
class JenisTender extends Model
{
    use HasFactory;
    protected $table = 'jenis_tender';
    protected $fillable = ['id', 'nama', 'updated_at', 'created_at'];

    /**
     * Function for relationship one to many
     */
    public function mappingJenisIklan()
    {
        return $this->hasMany(MappingJenisIklan::class, 'id');
    }

}
