<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace Modules\Sisdant\Models;

use Modules\Sisdant\Models\PermohonanNomborPerolehan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class JenisIklan.
 */
class KategoriIklan extends Model
{
    use HasFactory;
    protected $table = 'kategori_iklan';
    protected $fillable = ['id', 'nama', 'updated_at', 'created_at'];

    /**
     * Function for relationship one to many
     */
    public function mohonNomborPerolehan()
    {
        return $this->hasMany(PermohonanNomborPerolehan::class, 'id');
    }
}
