<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace Modules\Sisdant\Models;

use Modules\Sisdant\Models\JenisIklan;
use Modules\Sisdant\Models\KategoriPerolehan;
use Modules\Sisdant\Models\JenisTender;
use Modules\Sisdant\Models\PermohonanNomborPerolehan;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class MatrikIklan.
 */
class MatrikIklan extends Model
{
    use HasFactory;
    protected $table = 'matrik_iklan';
    protected $fillable = [
        'id',
        'jenis_iklan_id',
        'kategori_perolehan_id',
        'jenis_tender_id',
        'upload_iklan',
        'updated_at',
        'created_at'
    ];

    /**
     * Function for belongs to relationship
     */
    public function jenisIklan()
    {
        return $this->belongsTo(JenisIklan::class, 'jenis_iklan_id');
    }

    /**
     * Function for belongs to relationship
     */
    public function kategoriPerolehan()
    {
        return $this->belongsTo(KategoriPerolehan::class, 'kategori_perolehan_id');
    }

    /**
     * Function for belongs to relationship
     */
    public function jenisTender()
    {
        return $this->belongsTo(JenisTender::class, 'jenis_tender_id');
    }

    /**
     * Function for belongs to relationship
     */
    public function mohonNo()
    {
        return $this->hasMany(PermohonanNomborPerolehan::class, 'id');
    }
}
