<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Http\Requests\Backend\Iklan;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Class StoreMatrikIklanRequest.
 */
class StoreMatrikIklanRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'jenis_iklan_id' => ['required', 'max:100'],
            'kategori_perolehan_id' => ['required', 'max:100'],
            'jenis_tender_id' => ['max:100'],
            'upload_iklan' => ['required', 'max:100'],
        ];
    }
}
