<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Services;

use App\Domains\Auth\Events\Iklan\JenisIklanCreated;
use App\Domains\Auth\Events\Iklan\JenisIklanUpdated;
use App\Domains\Auth\Events\Iklan\JenisIklanDeleted;
use Modules\Sisdant\Models\JenisIklan;
use App\Exceptions\GeneralException;
use App\Services\BaseService;
use Exception;
use Illuminate\Support\Facades\DB;

/**
 * Class IklanService.
 */
class JenisIklanService extends BaseService
{
    /**
     * IklanService constructor.
     *
     * @param JenisIklan $jenisIklan
     */
    public function __construct(JenisIklan $jenisIklan)
    {
        $this->model = $jenisIklan;
    }

    /**
     * @param  array $data
     * @return JenisIklan
     *
     * @throws GeneralException
     * @throws \Throwable
     */
    public function store(array $data = []): JenisIklan
    {
        DB::beginTransaction();

        try {
            $maxId = JenisIklan::max('id');
            $jenisIklan = $this->model::create(['id' => $maxId + 1, 'nama' => $data['nama']]);
        } catch (Exception $e) {
            DB::rollBack();

            throw new GeneralException(__('Sila cuba semula.'));
        }

        event(new JenisIklanCreated($jenisIklan));

        activity('Tetapan')
        ->performedOn($jenisIklan)
        ->log(':causer.name menambah jenis iklan :subject.nama');

        DB::commit();

        return $jenisIklan;
    }

    /**
     * @param  JenisIklan  $jenisIklan
     * @param  array $data
     *
     * @throws GeneralException
     * @throws \Throwable
     */
    public function update(JenisIklan $jenisIklan, array $data = []): JenisIklan
    {
        DB::beginTransaction();

        try {
            $jenisIklan->update(['nama' => $data['nama']]);
        } catch (Exception $e) {
            DB::rollBack();

            throw new GeneralException(__('Sila cuba semula'));
        }

        event(new JenisIklanUpdated($jenisIklan));

        activity('Tetapan')
        ->performedOn($jenisIklan)
        ->log(':causer.name mengemaskini jenis iklan :subject.nama');

        DB::commit();

        return $jenisIklan;
    }

    /**
     * @param  JenisIklan $jenisIklan
     * @return bool
     *
     * @throws GeneralException
     */
    public function destroy(JenisIklan $jenisIklan): bool
    {

        if ($this->deleteById($jenisIklan->id)) {
            event(new JenisIklanDeleted($jenisIklan));

            return true;
        }

        throw new GeneralException(__('Sila cuba semula'));
    }
}
