<?php
// phpcs:ignoreFile -- this fail is generated by Laravel
namespace App\Domains\Auth\Services;

use App\Domains\Auth\Events\Iklan\MatrikIklanCreated;
use App\Domains\Auth\Events\Iklan\MatrikIklanDeleted;
use App\Domains\Auth\Events\Iklan\MatrikIklanUpdated;
use Modules\Sisdant\Models\MatrikIklan;
use App\Exceptions\GeneralException;
use App\Services\BaseService;
use Exception;
use Illuminate\Support\Facades\DB;

/**
 * Class MatrikIklanService.
 */
class MatrikIklanService extends BaseService
{
    /**
     * MatrikIklanService constructor.
     *
     * @param MatrikIklan $matrikIklan
     */
    public function __construct(MatrikIklan $matrikIklan)
    {
        $this->model = $matrikIklan;
    }

/**
     * @param  array $data
     * @return MatrikIklan
     *
     * @throws GeneralException
     * @throws \Throwable
     */
    public function store(array $data = []): MatrikIklan
    {
        DB::beginTransaction();

        try {
            $maxId = MatrikIklan::max('id');
            $matrikIklan = $this->model::create([
                'id' => $maxId + 1,
                'jenis_iklan_id' => $data['jenis_iklan_id'],
                'kategori_perolehan_id' => $data['kategori_perolehan_id'],
                'jenis_tender_id' => $data['jenis_tender_id'],
                'upload_iklan' => $data['upload_iklan'],
            ]);
        } catch (Exception $e) {
            DB::rollBack();

            throw new GeneralException(__('Sila cuba semula.'));
        }

        event(new MatrikIklanCreated($matrikIklan));

        activity('Tetapan')
        ->performedOn($matrikIklan)
        ->log(':causer.name menambah matrik iklan :subject.id');

        DB::commit();

        return $matrikIklan;
    }

    /**
     * @param  MatrikIklan  $matrikIklan
     * @param  array $data
     * @return MatrikIklan
     *
     * @throws GeneralException
     * @throws \Throwable
     */
    public function update(MatrikIklan $matrikIklan, array $data = []): MatrikIklan
    {
        DB::beginTransaction();

        try {
            $matrikIklan->update([
                'jenis_iklan_id' => $data['jenis_iklan_id'],
                'kategori_perolehan_id' => $data['kategori_perolehan_id'],
                'jenis_tender_id' => $data['jenis_tender_id'],
                'upload_iklan' => $data['upload_iklan'],
        ]);
        } catch (Exception $e) {
            DB::rollBack();

            throw new GeneralException(__('Sila cuba semula'));
        }

        event(new MatrikIklanUpdated($matrikIklan));

        activity('Tetapan')
        ->performedOn($matrikIklan)
        ->log(':causer.name mengemaskini matrik iklan :subject.id');

        DB::commit();

        return $matrikIklan;
    }

    /**
     * @param  MatrikIklan $matrikIklan
     * @return bool
     *
     * @throws GeneralException
     */
    public function destroy(MatrikIklan $matrikIklan): bool
    {
        if ($this->deleteById($matrikIklan->id)) {
            event(new MatrikIklanDeleted($matrikIklan));

            return true;
        }

        throw new GeneralException(__('Sila cuba semula'));
    }
}
